export const API_BASE_URL = 'http://127.0.0.1:8000/api/';

export const ROLES = {
  SURVIVOR: 'Survivor',
  COUNSELOR: 'Counselor',
  ORG_STAFF: 'Org Staff',
  COUNTY_OFFICIAL: 'County Official',
  ADMIN: 'Admin',
};

export const COUNTIES = [
  'Nairobi', 'Mombasa', 'Kwale', 'Kilifi', 'Tana River', 'Lamu', 'Taita Taveta',
  'Garissa', 'Wajir', 'Mandera', 'Marsabit', 'Isiolo', 'Meru', 'Tharaka-Nithi',
  'Embu', 'Kitui', 'Machakos', 'Makueni', 'Nyandarua', 'Nyeri', 'Kirinyaga',
  'Murang\'a', 'Kiambu', 'Turkana', 'West Pokot', 'Samburu', 'Trans Nzoia',
  'Uasin Gishu', 'Elgeyo Marakwet', 'Nandi', 'Baringo', 'Laikipia', 'Nakuru',
  'Narok', 'Kajiado', 'Kericho', 'Bomet', 'Kakamega', 'Vihiga', 'Bungoma',
  'Busia', 'Siaya', 'Kisumu', 'Homa Bay', 'Migori', 'Kisii', 'Nyamira'
];

export const TRANSLATIONS = {
  en: {
    title: 'AmakaziWatch',
    subtitle: 'People Watch. Protecting Together.',
    slogan: 'AmakaziWatch provides a secure, trauma-informed platform for reporting incidents, finding immediate support, and monitoring safety trends across Kenya.',
    emergencyHelpline: 'Emergency Helpline',
    confidentialReporting: '100% Confidential Reporting',
    directCoordination: 'Direct NGO Coordination',
    reportNow: 'Report Now',
    reportNowDesc: 'Submit an incident report securely. You can remain anonymous.',
    findHelp: 'Find Help',
    findHelpDesc: 'Connect with legal aid, counselors, and safe houses near you.',
    browseResources: 'Browse Resources',
    safetyGuides: 'Safety Guides',
    ourPartners: 'Our Partners',
    liveSafetyInsights: 'Live Safety Insights',
    activeCases: 'Active Cases Monitored',
    helpLineCalls: 'Helpline Calls (24h)',
    highReportZones: 'High Report Zones',
    confidentialityPriority: 'Confidentiality as a Priority',
    confidentialityDesc: 'We partner with Kenya\'s leading NGOs, law enforcement, and medical providers to ensure that every report leads to action while protecting your identity.',
    safetyCheckIn: 'Safety Check-In',
    safetyCheckInDesc: 'If you don\'t check in by the timer\'s end, your emergency contacts will be notified with your location.',
    startTimer: 'Start Safety Timer',
    instantSos: 'Instant SOS',
    instantSosDesc: 'Press and hold for 3 seconds to alert emergency contacts and share real-time location.',
    manageContacts: 'Manage Contacts',
    riskAssessment: 'Risk Assessment',
    riskAssessmentDesc: 'A confidential 10-question tool to evaluate your safety situation and receive tailored advice.',
    escapePlan: 'Escape Plan',
    escapePlanDesc: 'Generate a step-by-step departure strategy including packing lists and safe locations.',
    safeCall: 'Safe Call',
    safeCallDesc: 'Schedule a "checking-in" call from a discrete number to provide an excuse to leave a situation.',
    safeWordManager: 'Safe Word Manager',
    syncWithContacts: 'Sync with Contacts',
    changeWord: 'Change Word',
    mentalWellness: 'Mental Wellness Resources',
    localSafeHouses: 'Local Safe Houses',
    legalAidDirectory: 'Legal Aid Directory',
    timelineInteractions: 'Timeline of Interactions',
    emergencyAssistance: 'Emergency Assistance',
    activateSos: 'Activate SOS',
    reportStatus: 'Report Status',
    recentActivity: 'Recent Activity',
    home: 'Home',
    dashboard: 'Dashboard',
    reports: 'Reports',
    safety: 'Safety Hub',
    vault: 'Digital Vault',
    peerSupport: 'Peer Support',
    legalBot: 'Legal Bot',
    organisations: 'Organisations',
    scorecards: 'Scorecards',
    admin: 'Admin Panel',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log Out',
    login: 'Log In',
    register: 'Register',
    quickExit: 'Quick Exit',
    quickExitDesc: 'Redirects instantly to a neutral search page (e.g. Google weather) for privacy.',
  },
  sw: {
    title: 'AmakaziWatch',
    subtitle: 'Watu Wanalinda. Kulinda Pamoja.',
    slogan: 'AmakaziWatch inatoa jukwaa salama na linalojali kiwewe kwa kutoa ripoti za matukio, kupata usaidizi wa haraka, na kufuatilia mienendo ya usalama kote nchini Kenya.',
    emergencyHelpline: 'Nambari ya Dharura',
    confidentialReporting: 'Ripoti ya Siri ya 100%',
    directCoordination: 'Uratibu wa Moja kwa Moja wa NGO',
    reportNow: 'Ripoti Sasa',
    reportNowDesc: 'Tuma ripoti ya tukio kwa usalama. Unaweza kubaki bila jina.',
    findHelp: 'Pata Msaada',
    findHelpDesc: 'Ungana na msaada wa kisheria, washauri, na nyumba salama zilizo karibu nawe.',
    browseResources: 'Vinjari Rasilimali',
    safetyGuides: 'Mwongozo wa Usalama',
    ourPartners: 'Washirika Wetu',
    liveSafetyInsights: 'Takwimu za Usalama za Moja kwa Moja',
    activeCases: 'Kesi Zinazofuatiliwa',
    helpLineCalls: 'Simu za Dharura (Saa 24)',
    highReportZones: 'Maeneo yenye Ripoti Nyingi',
    confidentialityPriority: 'Usiri kama Kipaumbele',
    confidentialityDesc: 'Tunashirikiana na NGOs zinazoongoza nchini Kenya, vyombo vya sheria, na watoa huduma za afya ili kuhakikisha kila ripoti inasababisha hatua wakati wa kulinda utambulisho wako.',
    safetyCheckIn: 'Kujisajili kwa Usalama',
    safetyCheckInDesc: 'Usipojisajili kabla ya muda wa kisaidizi kuisha, anwani zako za dharura zitaarifiwa na eneo lako.',
    startTimer: 'Anza Kisaidizi cha Usalama',
    instantSos: 'SOS ya Haraka',
    instantSosDesc: 'Bonyeza na ushikilie kwa sekunde 3 ili kuwatahadharisha anwani za dharura na kushiriki eneo la sasa.',
    manageContacts: 'Dhibiti Anwani',
    riskAssessment: 'Tathmini ya Hatari',
    riskAssessmentDesc: 'Chombo cha maswali 10 cha siri cha kutathmini hali yako ya usalama na kupata ushauri maalum.',
    escapePlan: 'Mpango wa Kutoroka',
    escapePlanDesc: 'Tengeneza mkakati wa hatua kwa hatua wa kuondoka ikiwa ni pamoja na orodha za kufunganya na maeneo salama.',
    safeCall: 'Simu Salama',
    safeCallDesc: 'Panga simu ya "kuangalia hali" kutoka kwa nambari isiyoonekana ili kutoa udhuru wa kuondoka kwenye hali fulani.',
    safeWordManager: 'Kidhibiti cha Neno Salama',
    syncWithContacts: 'Sawazisha na Anwani',
    changeWord: 'Badilisha Neno',
    mentalWellness: 'Rasilimali za Afya ya Akili',
    localSafeHouses: 'Nyumba Salama za Kienyeji',
    legalAidDirectory: 'Orodha ya Msaada wa Kisheria',
    timelineInteractions: 'Mstari wa Muda wa Mwingiliano',
    emergencyAssistance: 'Msaada wa Dharura',
    activateSos: 'Washa SOS',
    reportStatus: 'Hali ya Ripoti',
    recentActivity: 'Shughuli za Hivi Karibuni',
    home: 'Nyumbani',
    dashboard: 'Eneo la Kazi',
    reports: 'Ripoti',
    safety: 'Kituo cha Usalama',
    vault: 'Kavazi ya Kidijitali',
    peerSupport: 'Msaada wa Rika',
    legalBot: 'Boti ya Sheria',
    organisations: 'Mashirika',
    scorecards: 'Kadi za Alama',
    admin: 'Jopo la Utawala',
    profile: 'Wasifu',
    settings: 'Mipangilio',
    logout: 'Ondoka',
    login: 'Ingia',
    register: 'Jisajili',
    quickExit: 'Toka Haraka',
    quickExitDesc: 'Inakupeleka mara moja kwenye ukurasa wa kawaida (kama vile hali ya hewa ya Google) kwa usiri.',
  }
};
